load(
    "glsl_binary.bzl",
    "glsl_binary",
)

package(default_visibility = [
    "//lib/display:__pkg__",
])

glsl_binary(
    name = "vert",
    src = "shader.vert",
)

glsl_binary(
    name = "frag",
    src = "shader.frag",
)
