cc_library(
    name = "eigen",
    hdrs = glob(["eigen-3.4.0/Eigen/**"]),
    # defines = [
    #     "EIGEN_MPL_ONLY",
    #     "EIGEN_NO_DEBUG",
    # ],
    visibility = [
        "//lib:__subpackages__",
        "//tests:__pkg__",
    ],
)
