cc_binary(
    name = "check_physical_device",
    srcs = ["check_physical_device.cpp"],
    linkopts = [
        "-lvulkan",
        "-ldl",
        "-lpthread",
        "-lX11",
        "-lXxf86vm",
        "-lXrandr",
        "-lXi",
    ],
)
